PATCH: semantic versioning

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -27,11 +27,8 @@
     git remote add origin ${GIT_PROJECT_URL}
 
 .increment_semantic_version: &increment_semantic_version |
-    if [ ! -f VERSION.txt ]; then
-        echo 0.1.-1 > VERSION.txt
-    fi
-
-    VERSION=$(cat VERSION.txt)
+    [ ! -f version.txt ] && echo 0.1.-1 > version.txt
+    VERSION=$(cat version.txt)
     MAJOR=$(echo $VERSION | cut -d\. -f1)
     MINOR=$(echo $VERSION | cut -d\. -f2)
     PATCH=$(echo $VERSION | cut -d\. -f3)
@@ -41,18 +38,18 @@
         PATCH) PATCH=$((PATCH + 1)) ;;
         MINOR) MINOR=$((MINOR + 1)) ; PATCH=0 ;;
         MAJOR) MAJOR=$((MAJOR + 1)) ; PATCH=0 ; MINOR=0 ;;
+        *) echo "Cannot increment version from commit"; exit 1 ;;
     esac
 
-    VERSION=${MAJOR}.${MINOR}.${PATCH}
+    export VERSION=${MAJOR}.${MINOR}.${PATCH}
+    echo $VERSION > version.txt
 
-    INIT_FILE=$(find . -maxdepth 2 -name '__init__.py')
+    INIT_FILE=$(find . -maxdepth 2 -name "__init__.py")
+    [ -z $INIT_FILE ] && echo "Can't find <module>.__init__.py" ; exit 1;
     if grep -q "__version__" $INIT_FILE; then
         sed -ri "s/([0-9]+\.[0-9]+\.[0-9])/${VERSION}/" $INIT_FILE
-    else
-        echo "__version__ = ${VERSION}" >> $INIT_FILE
+    else echo "__version__ = ${VERSION}" >> $INIT_FILE
     fi
-
-    echo $VERSION | tee VERSION.txt
 
  
 variables:
@@ -79,9 +76,7 @@ run unit tests:
         - *configiure_git_repo
 
         - git checkout master
-        - cat VERSION.txt
         - *increment_semantic_version
-        - cat VERSION.txt
         - git add .
         - git commit -m 'Test [skip ci]'
         - git push origin master
