PATCH: semantic versioning

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -46,7 +46,7 @@
     echo $VERSION > version.txt
 
     INIT_FILE=$(find . -maxdepth 2 -name "__init__.py")
-    [ -z $INIT_FILE ] && echo "Can't find <module>.__init__.py" ; exit 1;
+    [ -z $INIT_FILE ] && { echo "Can't find <module>.__init__.py" ; exit 1; }
     if grep -q "__version__" $INIT_FILE; then
         sed -ri "s/([0-9]+\.[0-9]+\.[0-9])/${VERSION}/" $INIT_FILE
     else echo "__version__ = ${VERSION}" >> $INIT_FILE
